2021-08-02 10:24:45,437 INFO    MainThread:72523 [wandb_setup.py:_flush():69] setting env: {}
2021-08-02 10:24:45,437 INFO    MainThread:72523 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-02 10:24:45,437 INFO    MainThread:72523 [wandb_init.py:_log_setup():337] Logging user logs to /home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/wandb/run-20210802_102445-1vhaf3g1/logs/debug.log
2021-08-02 10:24:45,437 INFO    MainThread:72523 [wandb_init.py:_log_setup():338] Logging internal logs to /home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/wandb/run-20210802_102445-1vhaf3g1/logs/debug-internal.log
2021-08-02 10:24:45,438 INFO    MainThread:72523 [wandb_init.py:init():370] calling init triggers
2021-08-02 10:24:45,438 INFO    MainThread:72523 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-08-02 10:24:45,438 INFO    MainThread:72523 [wandb_init.py:init():419] starting backend
2021-08-02 10:24:45,438 INFO    MainThread:72523 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-02 10:24:45,448 INFO    MainThread:72523 [backend.py:ensure_launched():135] starting backend process...
2021-08-02 10:24:45,475 INFO    MainThread:72523 [backend.py:ensure_launched():139] started backend process with pid: 72541
2021-08-02 10:24:45,493 INFO    MainThread:72523 [wandb_init.py:init():424] backend started and connected
2021-08-02 10:24:45,495 INFO    MainThread:72523 [wandb_init.py:init():472] updated telemetry
2021-08-02 10:24:45,496 INFO    MainThread:72523 [wandb_init.py:init():491] communicating current version
2021-08-02 10:24:46,201 INFO    MainThread:72523 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.11.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-02 10:24:46,201 INFO    MainThread:72523 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-08-02 10:24:46,474 INFO    MainThread:72523 [wandb_init.py:init():529] starting run threads in backend
2021-08-02 10:24:50,096 INFO    MainThread:72523 [wandb_run.py:_console_start():1624] atexit reg
2021-08-02 10:24:50,096 INFO    MainThread:72523 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.REDIRECT
2021-08-02 10:24:50,096 INFO    MainThread:72523 [wandb_run.py:_redirect():1503] Redirecting console.
2021-08-02 10:24:50,107 INFO    MainThread:72523 [wandb_run.py:_redirect():1559] Redirects installed.
2021-08-02 10:24:50,107 INFO    MainThread:72523 [wandb_init.py:init():554] run started, returning control to user process
2021-08-02 10:24:53,206 INFO    MainThread:72523 [wandb_run.py:_atexit_cleanup():1594] got exitcode: 0
2021-08-02 10:24:53,206 INFO    MainThread:72523 [wandb_run.py:_restore():1566] restore
2021-08-02 10:24:56,178 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 859
}

2021-08-02 10:24:56,480 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 859
}

2021-08-02 10:24:57,489 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 1136
}

2021-08-02 10:24:57,814 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:57,916 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,017 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,119 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,220 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,322 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,423 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:58,525 INFO    MainThread:72523 [wandb_run.py:_wait_for_finish():1716] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 11771
}

2021-08-02 10:24:59,830 INFO    MainThread:72523 [wandb_run.py:_show_files():1938] logging synced files
